"use client";

import Link from 'next/link';

export default function ReviewQueue() {
  // Convex Stub
  // const pendingAssets = useQuery(api.campaigns.getPendingReview);

  return (
    <div className="min-h-screen bg-[#fff4f3] font-['Inter'] pb-32">
      <header className="pt-10 px-8 max-w-6xl mx-auto flex items-center justify-between">
        <div>
          <h1 className="text-4xl font-bold text-[#ac2c00] tracking-tight">Review Queue</h1>
          <p className="text-[#834c4b] mt-1 font-medium">Assets generated by LangGraph requiring Human-in-the-Loop approval.</p>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-8 mt-12 space-y-8">
        <section className="bg-white rounded-3xl p-8 shadow-[0_20px_40px_rgba(78,33,33,0.04)] ring-1 ring-[#ffd2d0]/50">
          <div className="flex space-x-6 mb-8 border-b border-[#ffe1e0]">
            <button className="pb-4 font-bold text-[#ac2c00] border-b-2 border-[#FF4500]">Pending Action (2)</button>
            <button className="pb-4 font-bold text-[#cd8c8a] hover:text-[#834c4b]">Recently Approved</button>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Link href="/review/asset/asset_pulsefit_01">
              <div className="bg-[#ffedeb] rounded-2xl p-6 border border-[#ffd2d0] hover:-translate-y-1 hover:shadow-lg hover:shadow-[#FF4500]/10 transition-all cursor-pointer h-full flex flex-col">
                 <div className="flex justify-between items-start mb-4">
                   <h3 className="text-lg font-bold text-[#ac2c00]">PulseFit Insta Reel</h3>
                   <span className="bg-amber-100 text-amber-800 text-xs font-bold px-2 py-1 rounded-full">Requires Review</span>
                 </div>
                 <p className="text-sm text-[#834c4b] mb-4">Format: Instagram Reel<br/>Region: North America</p>
                 <div className="mt-auto text-sm font-bold text-[#FF4500] flex items-center">
                    Review Asset ➔
                 </div>
              </div>
            </Link>

            <Link href="/review/asset/asset_pulsefit_02">
              <div className="bg-[#ffedeb] rounded-2xl p-6 border border-[#ffd2d0] hover:-translate-y-1 hover:shadow-lg hover:shadow-[#FF4500]/10 transition-all cursor-pointer h-full flex flex-col">
                 <div className="flex justify-between items-start mb-4">
                   <h3 className="text-lg font-bold text-[#ac2c00]">PulseFit Email Sequence</h3>
                   <span className="bg-amber-100 text-amber-800 text-xs font-bold px-2 py-1 rounded-full">Requires Review</span>
                 </div>
                 <p className="text-sm text-[#834c4b] mb-4">Format: Email Promo<br/>Region: Europe</p>
                 <div className="mt-auto text-sm font-bold text-[#FF4500] flex items-center">
                    Review Asset ➔
                 </div>
              </div>
            </Link>
          </div>
        </section>
      </main>
    </div>
  );
}
